trigger:
  batch: true
  branches:
    include:
      - main
      - hotfix/*
  # paths:
  #   exclude:
  #     - devops/Terraform
  #     - devops/infra-*

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  major: 1
  minor: 2
  run.sonar: true
  run.tests: true
  build.compileMigrationDesignerFiles: true # Compilation of EF designer files
  sonarCloud.endpoint: "ObeliskSonarCloud" # Service connection as it stands in Azure DevOps

stages:
  - stage: Set_Build_Number # There is no much reason to make it as a stage. It could also be a first job of the BuildAndPublishArtifacts stage
    displayName: "Set Build Number"
    dependsOn: []
    jobs:
      - job:
        displayName: "Set Build Number"
        variables:
          buildPatch: $[counter(format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['Build.SourceBranch']), 1)]
          buildHotfix: $[counter(variables['Build.SourceBranch'], 1)]
        steps:
          - checkout: none
          - bash: |
              hotfixBranchRegex='^refs\/heads\/hotfix\/(.+)'
              buildNumberRegex='^[0-9]+\.[0-9]+\.[0-9]+$'
              buildNumber='N/A'
              [[ "$(Build.SourceBranch)" =~ $hotfixBranchRegex ]] \
                && \
                  (buildNumberPrefix="${BASH_REMATCH[1]}"; \
                   echo "Build Number Prefix: $buildNumberPrefix"; \
                   [[ "$buildNumberPrefix" =~ $buildNumberRegex ]] \
                    && \
                      (buildNumber="$buildNumberPrefix"."$(buildHotfix)"; \
                       echo "Setting Build Number: $buildNumber"; \
                       echo "##vso[build.updatebuildnumber]$buildNumber") \
                    || \
                      >&2 echo "The '/hotfix/*' branch should follow the following format '/hotfix/major.minor.patch'") \
                || \
                  (buildNumber="$(major)"."$(minor)"."$(buildPatch)"; \
                   echo "Setting Build Number: $buildNumber"; \
                   echo "##vso[build.updatebuildnumber]$buildNumber")
            displayName: "Set Build Number"
            failOnStderr: true

  - stage: Build_And_Publish_Artifacts
    displayName: "Build & Publish Artifacts"
    dependsOn: [Set_Build_Number]
    jobs:
      - template: "build-jobs.yml"
        parameters:
          publishArtifacts: true
