export default {
    en: {
        application: {
            applicationName: 'Waterloo Template',
            developedBy: 'Developed by',
            version: 'Version',
            language: 'English'
        },
        button: {
            authSettings: 'Authentication settings',
            cancel: 'Cancel',
            changePassword: 'Change password',
            change: 'Change',
            close: 'Close',
            createNew: 'Create new',
            delete: 'Delete',
            download: 'Download',
            edit: 'Edit',
            export: 'Export',
            exportExcel: 'Export as Excel',
            exportPdf: 'Export as PDF',
            save: 'Save changes',
            resetPassword: 'Reset password',
            yes: 'Yes',
            no: 'No',
            remove: 'Remove',
            upload: 'Upload',
            logout: 'Logout',
            login: 'Login',
            unlock: 'Unlock',
            submit: 'Submit',
            viewDetails: 'View Details',
            update: 'Update',
            copy: 'Copy',
            select: 'Select',
            back: 'Back',
            backToLogin: 'Back to login page',
            goToHome: 'Back to Home'
        },
        imageAltText: {
            entityImage: 'Entity image',
            logoImage: 'Waterloo Template Homepage'
        },
        layout: {
            dashboard: 'Dashboard',
            users: 'Users',
            fileManager: 'File Manager',
            anemicModel: 'Anemic Model',
            anemicCustomers: 'Customers',
            anemicProducts: 'Products',
            anemicPurchaseOrders: 'Purchase Orders',
            anemicTags: 'Tags',
            richModel: 'Rich Model',
            richCustomers: 'Customers',
            richProducts: 'Products',
            richPurchaseOrders: 'Purchase Orders',
            richTags: 'Tags',
            syncFusion: 'Syncfusion',
            syncFusionCustomers: 'Customers',
            syncFusionProducts: 'Products',
            syncFusionPurchaseOrders: 'Purchase Orders',
            syncFusionTags: 'Tags',
            syncFusionProductsCheckbox: 'Products (Checkbox Selection)',
            syncFusionCustomersMenu: 'Customers (Menu)',
            syncFusionPurchaseOrdersFrozen: 'Purchase Orders (Frozen)',
            changePassword: 'Change Password',
            logout: 'Logout',
            authenticationSettings: 'Authentication Settings',
            navigation: 'Navigation',
        },
        message: {
            addEditEntityTitle: 'Add/Edit',
            search: 'Search',
            currentFolder: 'Current folder:',
            yes: 'Yes',
            no: 'No',
            itemsInCollection: 'items in collection',
            noElementsFound: 'No elements found'
        },
        notifications: {
            successTitle: 'Upload Successful',
            successMessage: 'File was uploaded successfully',
            failTitle: 'Upload Failed',
            failMessage: 'File was not uploaded successfully, please try again',
            pageNotFound: 'Oops! Page not found'
        },
        placeholder: {
            multiSelectSearch: 'Type to search',
            select: '- Select -',
            multiSelectSearchAddYourOwn: 'Type to search or add your own',
            search: 'Search...',
            imageDrop: 'Drop image here or',
            fileDrop: 'Drop file here or',
            clickToUpload: 'click to upload',
            pleaseSelect: 'Please select...',
            pickADate: 'Pick a date',
            rangeSeparator: 'To',
            startDate: 'Start date',
            endDate: 'End date'
        },
        // DEFAULTS FOR TABLES
        syncfusion: {
            grid: {
                emptyRecord: 'No records to display',
                true: 'true',
                false: 'false',
                invalidFilterMessage: 'Invalid Filter Data',
                groupDropArea: 'Drag a column header here to group its column',
                unGroup: 'Click here to ungroup',
                groupDisable: 'Grouping is disabled for this column',
                filterbarTitle: '\s filter bar cell',
                emptyDataSourceError: 'DataSource must not be empty at initial load since columns are generated from dataSource in AutoGenerate Column Grid',
                add: 'Add',
                edit: 'Edit',
                cancel: 'Cancel',
                update: 'Update',
                delete: 'Delete',
                print: 'Print',
                pdfexport: 'PDF Export',
                excelexport: 'Excel Export',
                wordexport: 'Word Export',
                csvexport: 'CSV Export',
                search: 'Search',
                columnchooser: 'Columns',
                save: 'Save',
                item: 'item',
                items: 'items',
                editOperationAlert: 'No records selected for edit operation',
                deleteOperationAlert: 'No records selected for delete operation',
                saveButton: 'Save',
                okButton: 'OK',
                cancelButton: 'Cancel',
                editFormTitle: 'Details of',
                addFormTitle: 'Add New Record',
                batchSaveConfirm: 'Are you sure you want to save changes?',
                batchSaveLostChanges: 'Unsaved changes will be lost.Are you sure you want to continue?',
                confirmDelete: 'Are you sure you want to Delete Record?',
                cancelEdit: 'Are you sure you want to Cancel the changes?',
                chooseColumns: 'Choose Column',
                searchColumns: 'search columns',
                matchs: 'No Matches Found',
                filterButton: 'Filter',
                clearButton: 'Clear',
                startsWith: 'Starts With',
                endsWith: 'Ends With',
                contains: 'Contains',
                equal: 'Equal',
                notEqual: 'Not Equal',
                lessThan: 'Less Than',
                lessThanOrEqual: 'Less Than Or Equal',
                greaterThan: 'Greater Than',
                greaterThanOrEqual: 'Greater Than Or Equal',
                chooseDate: 'Choose a Date',
                enterValue: 'Enter the value',
                copy: 'Copy',
                group: 'Group by this column',
                ungroup: 'Ungroup by this column',
                autoFitAll: 'AutoFit all columns',
                autoFit: 'AutoFit this column',
                export: 'Export',
                firstPage: 'First Page',
                lastPage: 'Last Page',
                previousPage: 'Previous Page',
                nextPage: 'Next Page',
                sortAscending: 'Sort Ascending',
                sortDescending: 'Sort Descending',
                editRecord: 'Edit Record',
                deleteRecord: 'Delete Record',
                filterMenu: 'Filter',
                selectAll: 'Select All',
                blanks: 'Blanks',
                filterTrue: 'True',
                filterFalse: 'False',
                noResult: 'No Matches Found',
                clearFilter: 'Clear Filter',
                numberFilter: 'Number Filters',
                textFilter: 'Text Filters',
                dateFilter: 'Date Filters',
                matchCase: 'Match Case',
                between: 'Between',
                customFilter: 'Custom Filter',
                customFilterPlaceHolder: 'Enter the value',
                customFilterDatePlaceHolder: 'Choose a date',
                and: 'AND',
                or: 'OR',
                showRowsWhere: 'Show rows where:'
            },
            pager: {
                currentPageInfo: '{0} of {1} pages',
                totalItemsInfo: '({0} items)',
                totalItemInfo: '({0} item)',
                firstPageTooltip: 'Go to first page',
                lastPageTooltip: 'Go to last page',
                nextPageTooltip: 'Go to next page',
                previousPageTooltip: 'Go to previous page',
                nextPagerTooltip: 'Go to next pager',
                previousPagerTooltip: 'Go to previous pager',
                pagerDropDown: 'Items per page',
                pagerAllDropDown: 'Items',
                all: 'All',
            },
            formValidator: {
                required: 'This field is required.',
                email: 'Please enter a valid email address.',
                url: 'Please enter a valid URL.',
                date: 'Please enter a valid date.',
                dateIso: 'Please enter a valid date (ISO).',
                number: 'Please enter a valid number.',
                digit: 'Please enter only digits.',
                maxLength: 'Please enter no more than {0} characters.',
                minLength: 'Please enter at least {0} characters.',
                rangeLength: 'Please enter a value between {0} and {1} characters long.',
                range: 'Please enter a value between {0} and {1}.',
                max: 'Please enter a value less than or equal to {0}.',
                min: 'Please enter a value greater than or equal to {0}.',
                regex: 'Please enter a correct value.',
                exactLength: 'This field must contain the correct number of characters.'
            }
        },
        vueTables: {
            count: 'Showing {from} to {to} of {count} records|{count} records|One record',
            first: 'First',
            last: 'Last',
            filter: '',
            filterPlaceholder: 'Search query',
            limit: 'Records:',
            page: 'Page:',
            noResults: 'No matching records',
            noRequest: 'Please select at least one filter to fetch results',
            filterBy: 'Filter by {column}',
            loading: 'Loading...',
            defaultOption: 'Select {column}',
            columns: 'Columns'
        }
    }
}